# .streamlit/secrets.toml

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1yNcsYBRmUJREstZkIMikr7yLo-ytAUPd2lZPBISAsv4/edit?usp=sharing"

[auth]
license_key = "Rano 2912"
